### ISSUE TITLE
accept other escapes for arrows

### ISSUE THREAD

**Issue by tpapp** [nick-paul/TerminalMenus.jl#12]
I was directed here from https://github.com/JuliaLang/Pkg3.jl/issues/61. I have looked at the sources and it seems that the problem is that `ansi-term` in Emacs sends `\eOA` etc as the arrow keys, `TerminalMenus.jl` expects `\e[A` etc.

While `ansi-term`s codes [can be changed](https://github.com/emacs-mirror/emacs/blob/cda4c74e60962a49908d130f6dd70b0ae90a0255/lisp/term.el#L53-L56), the change is global, not buffer-specific. So if possible, it would be great if `TerminalMenus.jl` could also accept `\eOA` (up), `\eOB` (down), `\eOC` (right), `\eOD` (left).

**Comment by nick-paul** [comment]
Thanks for your patience.

@tpapp I added a few lines of code to the function that reads keyboard input that should make it compatible with Emacs `ansi-term`. If possible, can you verify that it is now working in your environment by running 
```
Pkg.checkout("TerminalMenus", "other-escapes")
```
and testing the arrow keys?

Thanks!

**Comment by tpapp** [comment]
It is working perfectly now, both on Julia `v0.6.2` and `master`. Thanks!

**Comment by nick-paul** [comment]
Great, thanks for checking!
