### ISSUE TITLE
press <enter> to select?

### ISSUE THREAD

**Issue by bjarthur** [nick-paul/TerminalMenus.jl#17]
currently the prompt for a MultiSelectMenu is `[press: d=done, a=all, n=none]`.  took me awhile to figure out that one should press `enter` to select.  how about changing the prompt to `[press: d=done, a=all, n=none, <enter>=select]` ?

**Comment by bjarthur** [comment]
to expand on this...

my initial guess was that since the up and down arrows are used to scroll through the list, that then to select an item the right arrow would be used, and to de-select the left arrow would be used.

when i figured out that the enter key was used to toggle the selection, i was surprised that it also did not advance the cursor to the next line down.

these two UIs are not mutually exclusive:  one could keep the functionality of the enter key to toggle the selection, and add to it the left/right arrow keys, plus the advance of the cursor.

i think the cursor advance is important, as it reduces the number of keystrokes by half if one needs to select or de-select a long contiguous set of items.

**Comment by nick-paul** [comment]
Thanks for the input, I also like the idea of advancing the cursor when pressing <enter> and using the left/right arrow keys for selection (without advancing). I'll see if I can add the mapping soon.
