### ISSUE TITLE
multi-select from a single choice

### ISSUE THREAD

**Issue by bjarthur** [nick-paul/TerminalMenus.jl#19]
my use case is that i programmatically calculate the choices from a search in a database, and then want to give the user the opportunity to manually prune a few bad results.  multi-select is perfect for this.

the problem is that on occasion there is just one entry in the database, and i'd still like to give the user the opportunity to discard it.  as terminalmenus.jl stands now, i have to add logic to handle this case.  would be better to remove the restriction that there must be at least two choices.  if you agree, i'm happy to work up a PR.  let me know.  thanks.

**Comment by nick-paul** [comment]
There was no reason for the limit other than the fact that never thought about them being used with <2 choices. I was able to remove the restriction in #20. Will it work for your use case?
