### ISSUE TITLE
Allow for preselected/default items

### ISSUE THREAD

**Issue by yakir12** [nick-paul/TerminalMenus.jl#23]
It would be cool to allow for some default or pre-selected item to be specified. 

To me it seems most logical to add an optional argument, say `default = 1`, to the `request` function. In the case of a `RadioMenu`, the default option will already have the cursor on it. In the case of the `MultiSelectMenu`, each of the indices in `default` will be prechecked when displayed.

Additionally, it could be cool to have the menu object remember the last choice and use that as the default. So `request` will update its menu object with the last choice and this will be used as the default value next time there is a request.

**Comment by yakir12** [comment]
Badabim Bada`bump`.

**Comment by christopher-dG** [comment]
I've had a PR for this open for some time in the stdlib version: https://github.com/JuliaLang/julia/pull/30043

Also about the "use the last selection" request: #3 is kind of related.

**Comment by KronosTheLate** [comment]
Note that this is implemented. Example below:
```
julia> import REPL; using REPL.TerminalMenus

julia> menu = MultiSelectMenu(["Op 1", "Op 2", "Op 3"], selected=(2, 3));

julia> request(menu)
[press: Enter=toggle, a=all, n=none, d=done, q=abort]
 > [ ] Op 1
   [X] Op 2
   [X] Op 3
```

Close this issue? In fact, issues should be raised at the julia repo, as it is a stdlib, right? So the ability to make and find issues here can lead to confusion.
